### ISSUE TITLE
html-template 0.22.x causes an error

### ISSUE THREAD

**Issue by pioneer2k** [asyncapi/github-action-for-generator#103]
#### Describe the bug
When using the html-template 0.22.x (maybe earlier) I get the following error in GitHub Actions:

Error: This template is not compatible with the current version of the generator (1.0.1). This template is compatible with the following version range: >=1.7.3 <2.0.0.

With html-template 0.20.1 everything is working.

#### How to Reproduce
use the github-action with html-template 0.22.3 like this

```
     - name: Generating HTML from AsyncAPI document
        uses: asyncapi/github-action-for-generator@v1.0.30
        with:
          template: '@asyncapi/html-template@0.22.3' 
          filepath: src/main/resources/asyncapi.yml
          parameters: baseHref=/customer-context-asyncapi-generated-html/
          output: asyncapi/customer-context-asyncapi-generated-html
```

#### Expected behavior
no error
