### ISSUE TITLE
Version 2.2.0 is not supported error

### ISSUE THREAD

**Issue by ysomad** [asyncapi/github-action-for-generator#166]
Got `Error: Version 2.2.0 is not supported.` when setting GH actions job.

Logs:
```sh
Run asyncapi/github-action-for-generator@v1
  with:
    template: @asyncapi/html-template@0.23.11
    filepath: backend/docs/asyncapi.yml
    parameters: baseHref=/test-experiment/ sidebarOrganization=byTags
    output: generated-html
(node:2002) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: Version 2.2.0 is not supported.
```

GH actions configuration:
```yml
name: AsyncAPI documents processing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Generating HTML from my AsyncAPI document
      uses: asyncapi/github-action-for-generator@v1
      with:
        template: '@asyncapi/html-template@0.23.11' # latest
        filepath: backend/docs/asyncapi.yml
        parameters: baseHref=/test-experiment/ sidebarOrganization=byTags
        output: generated-html
```
