### ISSUE TITLE
Version 2.4.0 not supported

### ISSUE THREAD

**Issue by victormartingarcia** [asyncapi/github-action-for-generator#232]
#### Describe the bug
The step to generate the HTML from the AsyncAPI document does not work with version `2.4.0`

<img width="1020" alt="Screenshot 2022-08-16 at 08 08 11" src="https://user-images.githubusercontent.com/659832/184809574-e8f455a3-26ce-4097-a036-7039d9df95bb.png">

#### How to Reproduce
Github action step:

```
    #In case you do not want to use defaults, you for example want to use different template
    - name: Generating HTML from my AsyncAPI document
      uses: docker://asyncapi/github-action-for-generator:2.0.3
      with:
        template: '@asyncapi/html-template@0.24.10'  #In case of template from npm, because of @ it must be in quotes
        filepath: CORE.yaml
        output: generated-html
```

AsyncAPI yaml file:

```
asyncapi: '2.4.0'
info:
  title: My service
  version: 0.0.1
  description: Service description
```
